<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nng 3 Li Ha Ca Cha_card-img-top</name>
   <tag></tag>
   <elementGuidId>4537fb98-9cf3-491f-a1bd-0cf876b8f39b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p19 > img.card-img-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p19']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>00b61e1d-3134-400d-96c2-b19877836280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bilutv.link/film/11986/poster.jpg?v=1639212169</value>
      <webElementGuid>4f3954c4-9f46-4e28-af68-11b1d42ea8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>fb69fdf3-11b4-41cf-b9b9-9153daa8b66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>p19</value>
      <webElementGuid>08c78d06-86e5-4571-bb46-596c63f9869c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list&quot;)/div[@class=&quot;list-newMovie&quot;]/div[@class=&quot;d-flex flex-row justify-content-around&quot;]/div[2]/div[@id=&quot;p19&quot;]/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>c56a832d-f76c-4870-aa3f-fde927fd62a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p19']/img</value>
      <webElementGuid>45cf7007-3cb8-4c6d-9601-cd58d740a712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='p19']</value>
      <webElementGuid>8433015e-19fc-41ce-b2b3-ffa436ee888b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/img</value>
      <webElementGuid>9319e48e-e981-48cc-b23e-e10116ba99bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bilutv.link/film/11986/poster.jpg?v=1639212169' and @alt = 'p19']</value>
      <webElementGuid>57c68470-02e7-4d2e-bc1d-67544c323283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
