<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Phim                            mi_card_5a78d6</name>
   <tag></tag>
   <elementGuidId>529fe0dd-25aa-40c7-9650-4bd92c18d268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.card-img-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p20']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>48f17bbd-d51c-48a3-8bf9-f85f597b66c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bilutv.link/film/19398/big.jpg</value>
      <webElementGuid>8d32a39d-7c6c-41c4-81f0-ba5aa4d4a972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>72f6bf0c-35c0-43cd-be75-56861b1f35e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>p20</value>
      <webElementGuid>8c92fa8b-2c48-42d7-9cfe-6e0b1b8ae9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list&quot;)/div[@class=&quot;list-newMovie&quot;]/div[@class=&quot;d-flex flex-row justify-content-around&quot;]/div[1]/div[@id=&quot;p20&quot;]/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>9079f9cb-f558-4f53-ae43-72c78811734d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p20']/img</value>
      <webElementGuid>fde4cd96-bd3a-43d1-8e07-c58bae4c7411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='p20']</value>
      <webElementGuid>d2645f5e-9b43-42b6-ba59-743dcf9ec9f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>c08ed2a9-d8ee-46a9-a361-02fc3e377dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bilutv.link/film/19398/big.jpg' and @alt = 'p20']</value>
      <webElementGuid>9d286fa6-bc65-452a-8be4-a17da579e491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
