<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_My Favorites_card-img-top</name>
   <tag></tag>
   <elementGuidId>3a01e6b7-b332-4931-8aa6-638c3810674c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.card-img-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p19']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b3008751-cfeb-4629-a8ab-294490b51ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bilutv.link/film/11986/poster.jpg?v=1639212169</value>
      <webElementGuid>50c8a1da-90c2-44d1-aa52-6867de7d98cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>215b904a-0bb9-430d-8739-78e93fa02004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>p19</value>
      <webElementGuid>9bcb55a4-2834-4e02-a6df-f3c93678eea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p19&quot;)/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>7096e667-68a6-4a10-8a38-76008708ccc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p19']/img</value>
      <webElementGuid>47097816-ac10-4d67-8122-11de271e5980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='p19']</value>
      <webElementGuid>9609875f-d6a6-43d3-bc2a-94e89863ca48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/img</value>
      <webElementGuid>cf1a58cb-3ebc-4e86-9c48-c9f66d4cf548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bilutv.link/film/11986/poster.jpg?v=1639212169' and @alt = 'p19']</value>
      <webElementGuid>d884baa7-c2e9-48b6-9d9f-47fabf529dfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
