<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>ea4f8b57-c8a6-4fe8-8298-8316217ba2c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.navbar-brand.text-white.dropdown-toggle.show > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>174cbffa-125b-4617-a34a-927ee462ec4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/User_cicrle_duotone.svg</value>
      <webElementGuid>996bf528-3de0-4d03-8b2b-52dbf6789d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/header[1]/div[@class=&quot;header d-flex justify-content-between rounded&quot;]/div[@class=&quot;dropdown&quot;]/a[@class=&quot;navbar-brand text-white dropdown-toggle show&quot;]/img[1]</value>
      <webElementGuid>7f5d53ba-58b0-4177-b453-cf102d8fcc1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>061df4d4-e1be-493b-9876-91eccfcb3ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/User_cicrle_duotone.svg']</value>
      <webElementGuid>27ad98eb-5aaa-4740-adfc-7f85e94cded1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
