<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ng</name>
   <tag></tag>
   <elementGuidId>e6f41462-946e-47df-ab26-bd73f915bcab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>19d701f3-fb15-4e7d-8aa6-6f1dbfe6e40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8b048a84-f71b-4982-ae53-875f9c2947cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>3bada383-75bc-469e-901c-13337c9d54af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng</value>
      <webElementGuid>c58447bb-6556-41e9-8633-3f88423b4f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;m-2&quot;]/div[@class=&quot;homepage&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;col-9&quot;]/div[@class=&quot;commentSession&quot;]/div[@class=&quot;user-comment&quot;]/form[@class=&quot;d-flex align-items-center justify-content-between&quot;]/button[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>c5d80c7e-ede0-4b7d-b67d-e65508a0a872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>09e9ff6e-d376-443e-a095-ce10d1aee238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Để lại bình luận'])[1]/following::button[1]</value>
      <webElementGuid>a9b94a4f-956f-4777-9c75-c17178f3871c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nguyễn Minh Trí'])[1]/following::button[1]</value>
      <webElementGuid>72bd8056-9a39-404e-bf13-1b043218fefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bảng xếp hạng'])[1]/preceding::button[1]</value>
      <webElementGuid>ab3b4f54-ece9-48ec-b7f3-38e3d221bd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cậu Bé Ma'])[1]/preceding::button[1]</value>
      <webElementGuid>d77a7a2b-bfa9-4a21-b69c-989de3f126a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đăng']/parent::*</value>
      <webElementGuid>a7b681a5-012d-48be-8a17-846273b45375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/button</value>
      <webElementGuid>483175f3-a47b-4ba3-8b67-ae318bf4c4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Đăng' or . = 'Đăng')]</value>
      <webElementGuid>22a7c283-5ad0-4bb6-94dc-d93ff9365ed1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
