<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_li bnh lun_curUserComment</name>
   <tag></tag>
   <elementGuidId>0ab896b2-4ecf-45dc-ab43-97e4a6e75d88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputlg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputlg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcd4b24a-8c0a-47fb-9e9c-9a98091819a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-lg </value>
      <webElementGuid>a030224e-eae5-42df-9a92-6372f9257ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputlg</value>
      <webElementGuid>0d6235f4-ff7c-4aa7-8f8c-177ab4e44933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>curUserComment</value>
      <webElementGuid>7e371062-3851-4398-a2b7-964daf4876d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>179d93b2-b278-42d0-8994-28b1bcccfea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập bình luận ở đây</value>
      <webElementGuid>0c12feda-7ac5-4067-a2bc-89e19e1e3b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputlg&quot;)</value>
      <webElementGuid>776994cc-2a5b-4e18-a0d5-5e3706c8c9c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputlg']</value>
      <webElementGuid>e0e02f80-5690-431c-a1c7-ac9700820387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ec1d4a2e-2408-4c36-b3e7-4f85dfe3d932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputlg' and @name = 'curUserComment' and @type = 'text' and @placeholder = 'Nhập bình luận ở đây']</value>
      <webElementGuid>bfc1dfa9-9f83-4f88-a070-bb6fc2be11de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
