<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_o din_director</name>
   <tag></tag>
   <elementGuidId>00037ec3-588e-4afa-be9c-99251ce556c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#director</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='director']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29bdbc9c-11e8-4fd1-bd74-72eba72a6423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a70e767-9a9b-4331-88dd-d3af762d4ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4f26fa62-faa0-481b-83a0-a9e54f9481bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>director</value>
      <webElementGuid>d81d7cab-763d-4f25-8d52-1af39f22a945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>director</value>
      <webElementGuid>b9530030-9aad-419e-9d33-585857c1ddd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;director&quot;)</value>
      <webElementGuid>60437bfd-a7de-4612-bb06-e4b4f7e23bb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='director']</value>
      <webElementGuid>31d7018b-3299-4d08-a5aa-5b6d2ac38ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>37af5257-6e14-4e65-82d1-9fbeaa4fa9a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'director' and @name = 'director']</value>
      <webElementGuid>f7914151-ec48-40c7-8b7e-b29aa3db3a2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
