<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Din vin_cast</name>
   <tag></tag>
   <elementGuidId>3c925e5b-8377-4aaa-b441-3c74b4858c6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cast</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cast']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5ec663c-abba-4f55-b1ab-94ae9c3a43cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ddc6184b-f3c1-4361-9689-de3e8186bcc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e98de87c-f396-437a-986f-effda4b9a31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cast</value>
      <webElementGuid>a37980cb-aab2-4a51-a5ad-5bd6e30d6138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cast</value>
      <webElementGuid>73fbd11f-fdff-4655-ae5d-282deb27c3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cast&quot;)</value>
      <webElementGuid>f0ebee65-3a56-491e-abeb-5d70c2d8f890</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cast']</value>
      <webElementGuid>879a8e0f-474a-43bd-bc40-2713bc106b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>173bbf08-0803-4adf-8811-340c3722654b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'cast' and @name = 'cast']</value>
      <webElementGuid>73111d37-cce0-4a60-9cbf-f9aa33fa8012</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
