<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Video_source</name>
   <tag></tag>
   <elementGuidId>ab6e6e81-311e-4c19-a75c-5631162b841d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#source</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='source']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>485ff4e9-845f-40cc-b84e-8bec5466651b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf02ba49-9c3c-409f-b2a9-cd2f3e6a1d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f983a916-60a1-4b71-a622-34b0d48b2907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>source</value>
      <webElementGuid>1f6755bb-b66e-4633-962a-effaaa6603ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>source</value>
      <webElementGuid>b3abff1c-5505-4f5d-a8ea-841433eb573c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;source&quot;)</value>
      <webElementGuid>289b239f-3fa1-47ce-8d5e-f6d09b0789d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='source']</value>
      <webElementGuid>59fe6064-cb56-4905-bea8-caad7972dd85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[9]</value>
      <webElementGuid>8ebfe311-de50-4561-b784-56acc9852db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'source' and @name = 'source']</value>
      <webElementGuid>adfe49fc-a1ff-4e0a-85da-a8c8402a08f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
