<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ni dung_synopsis</name>
   <tag></tag>
   <elementGuidId>e3e6d5c2-9844-42b3-9f35-f533b3069f22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#synopsis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='synopsis']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77356331-5f81-4295-a9c6-acff985fbf87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31249fb0-0bfb-4ef1-af45-92dc31ca7662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d418e6f7-f180-4a38-bbb6-86bf7f5d4762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>synopsis</value>
      <webElementGuid>38697d19-0c9a-4a0b-81f4-3653b2aa37ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>synopsis</value>
      <webElementGuid>8af9dcda-799d-4d6d-8732-edd0855a4d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;synopsis&quot;)</value>
      <webElementGuid>886fd336-c230-4868-9237-bfdddcc4a84a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='synopsis']</value>
      <webElementGuid>dbefc8d9-4152-41b2-90f3-cd90191eee2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[7]</value>
      <webElementGuid>8fab33f2-d9ce-4e00-beba-1f32d3210ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'synopsis' and @name = 'synopsis']</value>
      <webElementGuid>541a02d4-2d11-40a0-b5f7-c23528f2042d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
