<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hnh nh_img</name>
   <tag></tag>
   <elementGuidId>7729164d-e975-4e76-8136-dac601c141d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aeade66a-3dc1-49f7-8894-6193eea314bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8591f7c3-039e-405d-9e07-c3b21e3d127e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>16f8e085-6afe-4b0e-b2be-ecc3c5ba0f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6ed0b838-4c95-49bb-a6dc-d2a06a045afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ccaf5a66-cb1a-4883-b21f-335d8304e993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img&quot;)</value>
      <webElementGuid>9715ba5b-4382-4a5b-b887-dffe48047f6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='img']</value>
      <webElementGuid>4c1d24b7-2f2e-47b0-bc84-fcbddea6198d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[8]</value>
      <webElementGuid>9d0f59df-0b07-43e5-9538-53208c30d1c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'img' and @name = 'img']</value>
      <webElementGuid>44a5d2f3-903b-4633-bb04-0af59348b06a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
