<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Th loi_genres</name>
   <tag></tag>
   <elementGuidId>c7b9b4b4-3bf8-4d45-a7af-2ea4f768b142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#genres</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='genres']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1f3ee45-7e31-4a8f-bc4f-5dc290ca7677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>661a947d-8b80-49f4-a414-34022441f55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dcaa6434-86fc-404b-ad5d-30d5c7d044c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>genres</value>
      <webElementGuid>e2ce9bbd-b439-4a6d-b7ed-27070bd32331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>genres</value>
      <webElementGuid>894ee36b-d6b7-43a1-b294-3e69ec4a56d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;genres&quot;)</value>
      <webElementGuid>a6896a29-343f-470b-a17c-e38cd815b26c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='genres']</value>
      <webElementGuid>1040b16e-9359-48ed-81c1-5d726df9dc91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>35801019-510b-4f59-84a8-eaca74403d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'genres' and @name = 'genres']</value>
      <webElementGuid>09972dfe-1797-4646-91f3-341c421ac8e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
