<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rating 610 (2 lt)_star-10</name>
   <tag></tag>
   <elementGuidId>f1930597-e635-447e-982d-5cbdfc18da83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#star-10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='star-10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91aeb0ad-50a1-4de0-89ee-9ff0dda83300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>2826ba45-019e-49e7-ba35-5b330c9b20c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/material-symbols_star.svg</value>
      <webElementGuid>bb534c78-4749-4143-a460-36725b94be09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>star-10</value>
      <webElementGuid>7f992f62-63e7-4bdb-bc66-1708528645c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>colorChange(10)</value>
      <webElementGuid>164d717f-c94f-4c6f-bef1-2de0b5c7e91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Rating(10)</value>
      <webElementGuid>2ecd37ab-cbd7-4816-8fd3-bd46676efbf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>resetColor()</value>
      <webElementGuid>f43185c1-255e-433b-8664-4232b8a8182b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>aaf791ec-d4e8-4952-9835-29f11d6cd9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;star-10&quot;)</value>
      <webElementGuid>16510cfb-4e0a-4ebd-ba55-8589856726f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='star-10']</value>
      <webElementGuid>2601979b-8e9f-4ff5-9d1e-c937a03a3377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[11]</value>
      <webElementGuid>b70e0880-d2ab-4e89-98c8-022348c36a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @src = '/img/material-symbols_star.svg' and @id = 'star-10']</value>
      <webElementGuid>f808baae-2fb2-4194-8a8d-cfddf208d0f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
