<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rating 1010 (2 lt)_star-1</name>
   <tag></tag>
   <elementGuidId>0bc8eefa-a6e5-49ba-9824-588cda4e9e4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#star-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='star-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>398af68e-d98a-4b1e-a90c-dad8534b6afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>5d70ab66-0a64-4a78-850f-5cac834ce8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/material-symbols_star.svg</value>
      <webElementGuid>587593d8-adf6-460e-8acf-9f29dc2f23ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>star-1</value>
      <webElementGuid>56e282f4-70b0-4ef4-8279-84b8a4091f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>colorChange(1)</value>
      <webElementGuid>717b9fda-175d-4cce-8570-bcff76e87035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Rating(1)</value>
      <webElementGuid>90dd2a44-c9ef-40b0-8115-244e132a4c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>resetColor()</value>
      <webElementGuid>ae5d8e02-97c1-43b6-90d1-de36dcec18b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7f6abbd0-cc78-4a80-9415-c2b6c98d2660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;star-1&quot;)</value>
      <webElementGuid>7ad1aab2-1110-4952-8c90-04de3b83538f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='star-1']</value>
      <webElementGuid>eaf7593a-bcea-4f8a-b5b7-64460800b0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>a8fcda16-c3e0-4098-8621-ee5f75a50f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @src = '/img/material-symbols_star.svg' and @id = 'star-1']</value>
      <webElementGuid>94926a71-ee13-4edb-b866-07bc66e52c36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
