<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rating 9.510 (2 lt)_star-6</name>
   <tag></tag>
   <elementGuidId>59412b6c-c8a1-4962-a4da-3aa177e32e0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#star-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='star-6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c2d620b-06a9-4cac-ae76-61a94a2fd3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>01fc8a42-e5bb-4bff-b822-c7a6c147cc53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/material-symbols_star.svg</value>
      <webElementGuid>1bfd3a8f-3120-4926-9060-881b30a2e03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>star-6</value>
      <webElementGuid>6d115a5e-7642-4d65-a534-d7691b80423c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>colorChange(6)</value>
      <webElementGuid>8376bf01-6203-48e8-849d-49c9da14d5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Rating(6)</value>
      <webElementGuid>8455cb90-c44a-4707-acfd-c2929cf865da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>resetColor()</value>
      <webElementGuid>a144e7ac-3f8b-4f16-a110-b18b52986dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>1ca6ab56-1900-4076-bfc2-770fa92ae756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;star-6&quot;)</value>
      <webElementGuid>49ebd319-e10a-4501-af5f-7c3cc0fb79a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='star-6']</value>
      <webElementGuid>9fd183a6-9b15-40d6-9280-a1475377a0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[7]</value>
      <webElementGuid>166ff7d4-3db6-4c04-90c6-c628603e3e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @src = '/img/material-symbols_star.svg' and @id = 'star-6']</value>
      <webElementGuid>9d8146ad-d85a-4854-81de-581d4514e209</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
