<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rating 810 (2 lt)_star-2</name>
   <tag></tag>
   <elementGuidId>bfae0c6e-2b9b-4832-b391-82849a699b50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#star-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='star-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01080789-e2cb-4689-88ed-07d9ab8ea2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>1778eb07-d017-4c9b-a8a4-2fc5685a215b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/material-symbols_star.svg</value>
      <webElementGuid>786ba35c-1eba-4b5e-8f42-3b8e7f52f895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>star-2</value>
      <webElementGuid>4dcb1f59-cd47-47ba-b3be-1f339688fe55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>colorChange(2)</value>
      <webElementGuid>74525184-68b7-41cd-b488-b6aa8b50f9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Rating(2)</value>
      <webElementGuid>b0a2758e-ae08-4cbc-bfb6-a571974554df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>resetColor()</value>
      <webElementGuid>0f10663d-1867-485c-8510-fda34562534e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8ab57cdd-87f2-468f-806c-3319054bee58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;star-2&quot;)</value>
      <webElementGuid>652946bc-b47a-468e-8b77-7fc601487230</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='star-2']</value>
      <webElementGuid>55cf3c2e-d724-42b8-8c23-314f84549a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>5749bf39-f1bb-4e25-aa69-1761a4b34c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @src = '/img/material-symbols_star.svg' and @id = 'star-2']</value>
      <webElementGuid>674f79be-9bf1-4f08-8713-3710af88fbd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
