<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rating 1010 (1 lt)_star-9</name>
   <tag></tag>
   <elementGuidId>0b3b6119-bfd1-4efe-8dcb-f06e895b0dfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#star-9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='star-9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5450c65d-5899-4c87-b2fb-a08485b981ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>85e97ce4-b66e-453c-b97a-d68cf03c8b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/material-symbols_star.svg</value>
      <webElementGuid>dfb3fe3c-52eb-4597-be74-e39c67469994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>star-9</value>
      <webElementGuid>1630176b-e0f4-46d6-a3b9-80e87ff35600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseover</name>
      <type>Main</type>
      <value>colorChange(9)</value>
      <webElementGuid>42df3ccd-38a1-4a09-a64d-dcc0964fa30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Rating(9)</value>
      <webElementGuid>08a7640b-336a-48cf-838e-e3d41953a7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onmouseout</name>
      <type>Main</type>
      <value>resetColor()</value>
      <webElementGuid>b134e393-fcaa-44c0-8928-1ee05d8bc85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>77370a12-0772-4f98-8b93-0e4666622584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;star-9&quot;)</value>
      <webElementGuid>f7b88ec1-3aae-4249-89fc-6e863b3c8a3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='star-9']</value>
      <webElementGuid>c24fa121-3560-47fd-8618-1c3f8cc8aeb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[10]</value>
      <webElementGuid>45b07674-082e-431c-8843-d0c5a24ec59d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @src = '/img/material-symbols_star.svg' and @id = 'star-9']</value>
      <webElementGuid>fe59501a-b561-494c-8f09-0881b7a06005</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
