<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_M</name>
   <tag></tag>
   <elementGuidId>2a32ca6b-ef46-4293-bf6e-36a3dba49e57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.dropdown-menu.show > li > a.dropdown-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Mỹ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36593773-9f36-4ff9-9900-e0b29361c8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>82cd5167-3cca-4285-894b-a93b87bc9ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/country?country=Mỹ&amp;page=1</value>
      <webElementGuid>011a9a95-bb04-4ede-92f7-7824012927d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mỹ</value>
      <webElementGuid>4a6f8b9f-af6f-43b0-abff-f5f0266e2903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;m-2&quot;]/div[@class=&quot;homepage&quot;]/nav[@class=&quot;navbar mx-auto&quot;]/div[@class=&quot;navbar-nav d-flex flex-row justify-content-center align-items-center&quot;]/div[@class=&quot;dropdown nav-link&quot;]/ul[@class=&quot;dropdown-menu show&quot;]/li[1]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>f76b2446-bfdc-448c-96e9-c970e4c1e581</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mỹ')]</value>
      <webElementGuid>33b7a66f-61d0-4dde-b771-c5e56e00f986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quốc gia'])[1]/following::a[1]</value>
      <webElementGuid>378f4da6-340e-433d-af4e-3702cf2253fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Võ thuật, Kiếm Hiệp, Tâm lý, Tình cảm'])[1]/following::a[1]</value>
      <webElementGuid>24841a62-d02b-4532-90cc-c22da5505cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hàn Quốc'])[1]/preceding::a[1]</value>
      <webElementGuid>8cc5ee7f-6f70-4cd0-affa-70e5e02110d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Khác'])[1]/preceding::a[2]</value>
      <webElementGuid>1178b96e-c834-48c1-9b85-e369ff2f1822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mỹ']/parent::*</value>
      <webElementGuid>c3788b06-025a-4097-832d-a8856cc09989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/country?country=Mỹ&amp;page=1')]</value>
      <webElementGuid>c208ed2f-126b-4086-a1a9-5ba5ff55aed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/a</value>
      <webElementGuid>1fb82bd8-6da1-4a27-989e-2d564a538163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/country?country=Mỹ&amp;page=1' and (text() = 'Mỹ' or . = 'Mỹ')]</value>
      <webElementGuid>4c0b8607-6867-4ccc-bbaf-00991ec14e3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
