<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>2908682c-8798-4bba-982b-4afc0a0a1339</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='loadPage(2)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a0714e8a-c7f9-4183-95b4-82432a2dec0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link</value>
      <webElementGuid>5215a47c-47bd-4971-beba-b36688a11147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>loadPage(2)</value>
      <webElementGuid>17e61a17-a001-475b-ba2c-50fc163aefcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 2</value>
      <webElementGuid>64d03ed5-ec2e-447a-8191-b01b6766695a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list&quot;)/div[@class=&quot;page-list-movie&quot;]/nav[1]/ul[@class=&quot;pagination pagination-sm&quot;]/li[@class=&quot;page-item&quot;]/a[@class=&quot;page-link&quot;]</value>
      <webElementGuid>0a49b20c-d83c-468d-9ee4-1740df264bcd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='loadPage(2)']</value>
      <webElementGuid>f493ffa9-74a3-458a-a7b6-b3052c681a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list']/div[3]/nav/ul/li[2]/a</value>
      <webElementGuid>17437e6f-b5f2-4e59-94af-2645b66a8bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'2')]</value>
      <webElementGuid>e6461c4e-1fb6-43c5-9893-b3b229142c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đỉnh Mù Sương'])[1]/following::a[2]</value>
      <webElementGuid>5eb021a7-4c96-42e0-9fc5-593a4c6b15e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='p7'])[1]/following::a[2]</value>
      <webElementGuid>fbb86748-4294-48cb-9dde-b9ef70c0e70f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bảng xếp hạng'])[1]/preceding::a[2]</value>
      <webElementGuid>12689aa1-9110-4ca1-a1e5-bda8c4d9c829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cậu Bé Ma'])[2]/preceding::a[2]</value>
      <webElementGuid>e8a38e82-043f-4055-8665-5175899f853e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>218c2c36-6146-4bb5-937b-9b668ee9e787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[2]/a</value>
      <webElementGuid>7ca4c500-8136-46d3-8101-b98b7ff354f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' 2' or . = ' 2')]</value>
      <webElementGuid>e6207f11-f8d5-4e81-be23-85a08f50bc9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
