<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Em Cha 18_card-img-top</name>
   <tag></tag>
   <elementGuidId>a59e5718-2f04-4888-b08c-db5781e56d13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list']/div[3]/div/div[3]/div[3]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c516a937-5557-4513-8a57-ba255c25d81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bilutv.link/film/11912/big.jpg?v=1639321129</value>
      <webElementGuid>b82f183e-5ccc-4ff7-bf5c-16278a6538d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>3d162f70-fd69-43fe-8a9a-54a367055dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>p16</value>
      <webElementGuid>2c7c6167-7196-425b-9513-ad2e5b89d64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list&quot;)/div[@class=&quot;page-list-movie&quot;]/div[@class=&quot;cur-page&quot;]/div[@class=&quot;d-flex flex-row justify-content-around&quot;]/div[3]/div[@class=&quot;card position-relative&quot;]/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>ff722430-1110-471f-85c6-005437389348</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list']/div[3]/div/div[3]/div[3]/div/img</value>
      <webElementGuid>4349156e-7e19-49f2-bef7-cc61e6c0590d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='p16']</value>
      <webElementGuid>704e7c8a-d35e-49be-ab26-5bcea25b1cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/img</value>
      <webElementGuid>530c32e9-d0cf-4380-8eec-50961c2f1a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bilutv.link/film/11912/big.jpg?v=1639321129' and @alt = 'p16']</value>
      <webElementGuid>beb3e8c7-c7da-43a6-82db-c04f0d05eb0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
