<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Gi Gi Lm Chiu 2_card-img-top</name>
   <tag></tag>
   <elementGuidId>e4214c31-aa3a-48de-bcfc-3ece60e456f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p4 > img.card-img-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p4']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1b0db0ca-2918-40db-9562-db81cae0a430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bilutv.link/film/32016/poster.jpg?v=1668347205</value>
      <webElementGuid>3c432d90-46c2-4ec1-a7fe-c9453c5c286f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>fbc8379b-21b4-4fde-adff-1ddf93c58327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>p4</value>
      <webElementGuid>e44e3027-24f4-4ba1-86b0-83b5564ab21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p4&quot;)/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>544b5d05-e719-42af-b208-5ecb79fb21ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p4']/img</value>
      <webElementGuid>fc18b6ac-5476-4800-bbbe-ad398277d54f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='p4']</value>
      <webElementGuid>250c9d1c-2060-491f-a04d-50b829efb522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>5440ec4d-c218-4e64-bd67-d0e30d8885bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bilutv.link/film/32016/poster.jpg?v=1668347205' and @alt = 'p4']</value>
      <webElementGuid>ca632619-fe26-4b68-af30-2ab8daa82b5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
