<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Hells Kitchen_card-img-top</name>
   <tag></tag>
   <elementGuidId>a457d26a-bbc2-43dc-9e91-d0e19d604453</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p3 > img.card-img-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p3']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4ba55d46-4876-45eb-9757-ca5bd0af30b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bilutv.link/film/25092/poster.jpg?v=1657963291</value>
      <webElementGuid>a33bb173-cfac-4633-9cfb-7b469f4809aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>59e4412b-7e6f-44ee-9943-2ebf70752f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>p3</value>
      <webElementGuid>4ab636d2-592f-431c-9314-635bff7f7ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p3&quot;)/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>da66c7ef-473c-4fb8-8a76-78e2ab1f2780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p3']/img</value>
      <webElementGuid>48d7c008-efc2-4d1a-b7bf-5d19dd31ed60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='p3']</value>
      <webElementGuid>588143af-32d1-433f-a1b1-e6529729abfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/img</value>
      <webElementGuid>7971077a-7a12-4252-8b52-d02dead98eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bilutv.link/film/25092/poster.jpg?v=1657963291' and @alt = 'p3']</value>
      <webElementGuid>982fd491-5f19-4a4c-a3e0-2daaa2bdeff5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
