<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Annabelle 3_card-img-top</name>
   <tag></tag>
   <elementGuidId>c14d860b-cf13-41ca-90b9-edb7f8990121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p6 > img.card-img-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p6']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9ca31531-974a-4d32-9ea0-8d1f0b1ce7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bilutv.link/film/3202/poster.jpg</value>
      <webElementGuid>6dbd944c-5978-4c9e-97a3-071a01e0ef02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>7c7d5dc2-d349-473d-b576-fa54bc1fe63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>p6</value>
      <webElementGuid>bc9da904-74eb-4ad0-b0f0-00181e53f8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p6&quot;)/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>bf377a4a-9015-4e94-9d41-946017a49642</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p6']/img</value>
      <webElementGuid>0ca8cb6d-c9ce-4f77-afb7-0479e5470bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='p6']</value>
      <webElementGuid>b7f7f3e3-e81a-4bc7-9461-db39220ca534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/img</value>
      <webElementGuid>67b878f8-e602-42e1-a306-de22066de1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bilutv.link/film/3202/poster.jpg' and @alt = 'p6']</value>
      <webElementGuid>958e26c2-b759-4ff3-8ed7-d98b536044c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
