<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ng k_repassword</name>
   <tag></tag>
   <elementGuidId>cdfd6064-5aa1-46bb-abd2-0d7a33fc7edd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#repassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='repassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0205445b-9626-4338-9448-cdd94b5c8819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f07634b0-eebe-43d1-b1d2-29b128856196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repassword</value>
      <webElementGuid>8ccb8119-e2a0-4533-95c7-a7ad17ca1821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>repassword</value>
      <webElementGuid>9c7ed514-b389-4481-887a-295f354f66b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>xác nhận mật khẩu</value>
      <webElementGuid>15f33ea3-41a1-4eea-9124-e04a9bb6922c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repassword&quot;)</value>
      <webElementGuid>68f7fab1-3a8a-4fc1-b671-536381c20c51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='repassword']</value>
      <webElementGuid>1a9e3cd1-57f5-4bf0-9ea6-da948853118b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>61b19b00-0e92-4f3a-8401-12aeb29c71ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'repassword' and @id = 'repassword' and @placeholder = 'xác nhận mật khẩu']</value>
      <webElementGuid>39753f64-b097-4c9a-b104-96a84958813f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
