<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nng 3 Li Ha Ca Cha_card-img-top</name>
   <tag></tag>
   <elementGuidId>c20db114-f0a4-498a-b9a9-6aec718fe14f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p19 > img.card-img-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='p19']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b5f1fbb1-dfb6-45fe-a301-08fbc1b756ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bilutv.link/film/11986/poster.jpg?v=1639212169</value>
      <webElementGuid>f39df639-046d-4c13-ac17-0e9fa7f18604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>26f55732-079c-44c0-b039-ce45d9bf3f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>p19</value>
      <webElementGuid>b57f5ebc-9064-42c1-9704-a6fae9a05f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list&quot;)/div[@class=&quot;list-newMovie&quot;]/div[@class=&quot;d-flex flex-row justify-content-around&quot;]/div[2]/div[@id=&quot;p19&quot;]/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>6ea55840-29aa-42be-95c3-98d41db4b060</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p19']/img</value>
      <webElementGuid>f26486bc-bf4d-4e7e-9924-bdb9f0692bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='p19']</value>
      <webElementGuid>c273b637-6ced-46e5-b042-9401a6eb8341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/img</value>
      <webElementGuid>a30d5210-3e2c-4f1f-a10e-642a2c4f8e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bilutv.link/film/11986/poster.jpg?v=1639212169' and @alt = 'p19']</value>
      <webElementGuid>6ff11762-d9c2-4226-bf0a-728cb2287e08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
