<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ng xut_card-img-top</name>
   <tag></tag>
   <elementGuidId>e1a353dd-a057-4855-92b4-95eab16ec639</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.card-img-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='poster']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d5530f8d-6f7d-44c3-ba14-d51cdaa74377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bilutv.link/film/3202/poster.jpg</value>
      <webElementGuid>30ca7188-edb9-4344-881b-ef6593fe321d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>c4a5d7ec-3751-4cf0-acd3-8d4aa3a8998b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>poster</value>
      <webElementGuid>6c08d454-7156-4149-9b55-6ba25515c6c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;m-2&quot;]/div[@class=&quot;list-movies-update&quot;]/div[@class=&quot;movie&quot;]/a[1]/div[@class=&quot;card position-relative&quot;]/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>b460afff-3252-49e1-a1c3-0de7bccd224e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='poster']</value>
      <webElementGuid>9f4caa8d-e5d8-4233-9524-dbc2e8b33390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>6589568c-3d2b-4601-a5a2-983995146cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bilutv.link/film/3202/poster.jpg' and @alt = 'poster']</value>
      <webElementGuid>fab25ce7-c35e-4d0f-a38c-ae875f79e78a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
