<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nhn  xa_card-img-top</name>
   <tag></tag>
   <elementGuidId>d0921e15-820d-4172-9485-425313b0210c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.card-img-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='poster']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c5f32291-927a-4e6f-8e4f-0df4db0b11e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bilutv.link/film/3202/poster.jpg</value>
      <webElementGuid>11aa3414-fde3-4daf-b46d-653f6ca000b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>506fdd11-5478-493d-a5e6-4c33d1720dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>poster</value>
      <webElementGuid>7fef1cee-48fb-4828-b9d7-44823e5113c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;m-2&quot;]/div[@class=&quot;list-movies-update&quot;]/div[@class=&quot;movie&quot;]/form[1]/a[1]/div[@class=&quot;card position-relative&quot;]/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>67bd2239-7d0a-433c-9ea7-c0b86f74d695</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='poster']</value>
      <webElementGuid>b53e88f9-3244-4f1e-be04-3945104dc148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>902242a1-053b-4da8-9199-bafbfe57d26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bilutv.link/film/3202/poster.jpg' and @alt = 'poster']</value>
      <webElementGuid>f60654cb-711e-4a18-8690-c99aad9a9b73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
