<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_o din_director</name>
   <tag></tag>
   <elementGuidId>2d388389-91f9-4ade-b672-3052ec529ed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#director</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='director']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2a79623-ab0e-45da-9cfc-53c7dcbec74f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da30ebc7-0117-4940-9d0a-9018e1b6da39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6a1b5c0f-1287-4f94-abd7-d885ddbf94c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>director</value>
      <webElementGuid>ac369cdf-3c4f-44a1-b237-5522f6ef26fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>director</value>
      <webElementGuid>9ed9bc05-8bb3-4f33-be16-eca6f6c3059f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Lloyd Lee Barnett </value>
      <webElementGuid>4109fbe2-7a13-4aa9-8b9f-6dc3054cca1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;director&quot;)</value>
      <webElementGuid>511f8c86-77e4-4ce9-9bec-b0bef5e7fc5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='director']</value>
      <webElementGuid>908b9e30-b954-4007-98fa-1d1edd0722e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[5]</value>
      <webElementGuid>e87cec2b-ccf6-4d3e-884b-e883e6aecf14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'director' and @name = 'director']</value>
      <webElementGuid>f7df6b37-e8e5-4006-a013-2515e7919e60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
