<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Video_source</name>
   <tag></tag>
   <elementGuidId>3c7d14bd-46fc-426b-b3aa-d07233c760ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#source</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='source']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e22fbe5-0991-453a-99c2-2f255d205ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84796872-cbea-4c1d-8ff0-41e366ac7976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1f447532-c71e-43aa-b6f8-b45a94aacb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>source</value>
      <webElementGuid>0271c89e-855a-4f91-a4ac-9b8cf757d7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>source</value>
      <webElementGuid>4c6bf40c-33b2-4b3c-8169-5fa67eaa10d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/SCSkQWHhAIU</value>
      <webElementGuid>d0190efb-e1dc-4404-b763-951635dce9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;source&quot;)</value>
      <webElementGuid>be83a1ed-d1b8-47bc-8a5e-a6655dfc531c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='source']</value>
      <webElementGuid>5f5e1251-c6e2-49af-a746-9f17dfda1b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[9]</value>
      <webElementGuid>18013184-72bc-4c23-b300-c39d0bf678e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'source' and @name = 'source']</value>
      <webElementGuid>81ce1424-fa8d-4810-98ab-b4c98edc2c88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
