<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Din vin_cast</name>
   <tag></tag>
   <elementGuidId>3481ab64-4358-4cbe-8e48-8575222d327a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cast</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cast']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b54473c-a730-4ac4-8b61-3564ffda479f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31b6ca85-7e18-46a6-a87d-33b89ecd437f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ec038157-ddd1-4426-9fc8-16a1c3b3a3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cast</value>
      <webElementGuid>fbfdf125-a70e-4ea3-86e9-cd80c1aa06c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cast</value>
      <webElementGuid>4708081a-4cc0-4e56-84f1-d53e5aaadc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>N/A</value>
      <webElementGuid>b3ee4b5a-7888-4f12-9016-b582ed78f9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cast&quot;)</value>
      <webElementGuid>453d78db-c5e9-48bc-803d-322efa40946e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cast']</value>
      <webElementGuid>3e6f889c-7b51-4ef4-8fa5-1dfcc871ce3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>3913d5f8-41bc-4c09-a062-3870a786f68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'cast' and @name = 'cast']</value>
      <webElementGuid>5f72ff2f-d0d9-4f25-9574-2fd09aa7ba7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
