<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Th loi_genres</name>
   <tag></tag>
   <elementGuidId>2f37f93d-9410-4fb6-830e-a4faaa1c08f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#genres</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='genres']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>417d45e2-3b7e-4679-94f5-046d79bc668f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f17df9ec-9ab2-4ecb-9fe4-e85652db37b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3540ea2d-02f4-4ded-ad3c-fa1622556b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>genres</value>
      <webElementGuid>1685bea3-1b6d-4444-bff9-47e6b23d082f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>genres</value>
      <webElementGuid>64dbd908-ee21-4cf4-928b-40d703f0346a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Hành động,Phiêu Lưu,Khoa học,Chiến tranh</value>
      <webElementGuid>c145775e-2fb8-4b5c-b766-8ac0c55e3e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;genres&quot;)</value>
      <webElementGuid>a8eb6edc-be4d-41b6-9f79-14ddb01f3ea9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='genres']</value>
      <webElementGuid>c48668ff-eca4-456f-ac19-98c81af5b3b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>452c38e6-1ee9-4753-ad31-ceac47bc8888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'genres' and @name = 'genres']</value>
      <webElementGuid>7575a8bc-427c-4758-bebe-e1dd2394ea29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
