<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hnh nh_img</name>
   <tag></tag>
   <elementGuidId>a8ee97b5-808d-4a8b-bdfb-502d8de9c119</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1aa17cc2-2346-4f27-ba31-424713c279a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>38ed7f32-a417-49d7-8d97-16a246551d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8a4885a5-d03f-41e0-a82a-0cdc296e79ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aa662754-ad81-469e-b243-1e64fca9cc11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1dc74f69-a448-4db8-9884-034e0e404062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>https://bilutv.link/film/3202/poster.jpg</value>
      <webElementGuid>7d06da99-965d-45e2-80fd-ac10411d42f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img&quot;)</value>
      <webElementGuid>0e06c3d0-873c-4ef0-b6a9-ef637dba720f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='img']</value>
      <webElementGuid>4643d3c4-89ae-4462-b60d-ad786d8e50be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[8]</value>
      <webElementGuid>635f1f2d-4e5e-4a80-a5e6-fe5878d679a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'img' and @name = 'img']</value>
      <webElementGuid>3d4f9037-16f6-465c-b8be-b9df3d8605e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
