<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ni dung_synopsis</name>
   <tag></tag>
   <elementGuidId>063efa91-e9ef-4aec-aacc-fd7fa8732663</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#synopsis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='synopsis']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebd3916e-46ad-4760-81f8-903bdfa7e38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6248c69-ab57-43b3-8891-67f5cf22c4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cde12adb-bda6-4090-9c03-a2bb1ba28071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>synopsis</value>
      <webElementGuid>76e49d39-2c44-4b96-8aa3-b449d52629df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>synopsis</value>
      <webElementGuid>94d6b714-635a-4406-b166-ff4792e3123a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Thị Tộc Nhẫn Giả - Ninja Apocalypse là một bộ phim hành động phiêu lưu Mỹ 2014 của đạo diễn Lloyd Lee Barnett. Bị buộc tội ám sát thủ lĩnh Fumitaka (Cary-Hiroyuki Tagawa), Lost Ninja Clan phải chiến đấu theo cách của mình để ra khỏi một hầm hạt nhận dưới lòng đất chứa đầy đám zombie khát máu. Liệu Clan có rửa được tội và thoát khỏi địa ngục?</value>
      <webElementGuid>e4f10937-89f7-433d-a317-e5ac5b80ed71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;synopsis&quot;)</value>
      <webElementGuid>2ba79b81-8d26-41ef-8dbd-3ad5dbb10acb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='synopsis']</value>
      <webElementGuid>2c6c9835-fd4b-4a9e-adfe-697447698e83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[7]</value>
      <webElementGuid>f9b044cf-33f4-4176-9eee-5b7dfe633f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'synopsis' and @name = 'synopsis']</value>
      <webElementGuid>5d8e3365-a767-4e46-8d11-8a606082f082</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
