<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ng k_repassword</name>
   <tag></tag>
   <elementGuidId>ac807291-cdc0-49cf-8d88-770e8c0a1baf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#repassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='repassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7327bee2-dfd8-4b36-8ab0-74597686f6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>919aedb2-59a1-4683-9be7-d65451a9df57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repassword</value>
      <webElementGuid>a0ce3eea-c2f3-47c6-b6be-78ea67e61eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>repassword</value>
      <webElementGuid>528c3a7c-8682-4d06-a6fa-8c20ac6119ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>xác nhận mật khẩu</value>
      <webElementGuid>c687d37e-e273-4978-b7c0-f9c030802146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repassword&quot;)</value>
      <webElementGuid>f7c1ecde-0cd6-44a2-a05b-6d8b7f3ffa10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='repassword']</value>
      <webElementGuid>64a49d6d-6a28-4f53-8541-7df474f08722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>3b394e5e-9f99-45b6-a797-427759b68a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'repassword' and @id = 'repassword' and @placeholder = 'xác nhận mật khẩu']</value>
      <webElementGuid>e04ca772-20ba-4287-8660-fab94c22cf82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
